package reporter

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/haliminurja/vanguard/internal/models"
)

type MarkdownReporter struct {
	OutputDir string
	Version   string
}

func NewMarkdownReporter(outputDir string, version string) *MarkdownReporter {
	if outputDir == "" {
		outputDir = "."
	}
	if version == "" {
		version = "dev"
	}
	return &MarkdownReporter{OutputDir: outputDir, Version: version}
}

func (r *MarkdownReporter) Name() string   { return "markdown" }
func (r *MarkdownReporter) Format() string { return "md" }

func (r *MarkdownReporter) Generate(_ context.Context, report *models.ScanReport) error {
	if err := ensureOutputDir(r.OutputDir); err != nil {
		return err
	}

	counts := report.CountBySeverity()

	var sb strings.Builder
	sb.WriteString("# Vanguard Security Report\n\n")
	sb.WriteString(fmt.Sprintf("**Project:** %s  \n", report.ProjectContext.ProjectName))
	sb.WriteString(fmt.Sprintf("**Framework:** %s  \n", frameworkLabel(report.ProjectContext)))
	sb.WriteString(fmt.Sprintf("**PHP:** %s  \n", report.ProjectContext.PHPVersion))
	sb.WriteString(fmt.Sprintf("**Duration:** %s  \n", report.Duration.Round(1e6)))
	sb.WriteString(fmt.Sprintf("**Scanners:** %s  \n\n", strings.Join(report.ScannersRun, ", ")))
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Total | %d |\n", len(report.Findings)))
	sb.WriteString("|-------|---|\n")
	for _, sev := range []models.Severity{models.SeverityCritical, models.SeverityHigh, models.SeverityMedium, models.SeverityLow, models.SeverityInfo} {
		if c := counts[sev]; c > 0 {
			sb.WriteString(fmt.Sprintf("| %s %s | %d |\n", severityEmoji(sev), sev.String(), c))
		}
	}
	sb.WriteString("\n")
	sb.WriteString("## Findings\n\n")
	for _, sev := range []models.Severity{models.SeverityCritical, models.SeverityHigh, models.SeverityMedium, models.SeverityLow, models.SeverityInfo} {
		sevFindings := filterFindings(report.Findings, sev)
		if len(sevFindings) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("### %s %s (%d)\n\n", severityEmoji(sev), sev.String(), len(sevFindings)))

		for _, f := range sevFindings {
			classification := f.Classification()
			sb.WriteString(fmt.Sprintf("#### %s - %s\n\n", f.ID, f.Title))
			sb.WriteString(fmt.Sprintf("- **File:** `%s:%d`\n", f.File, f.Line))
			sb.WriteString(fmt.Sprintf("- **Category:** %s\n", f.Category))
			sb.WriteString(fmt.Sprintf("- **Class:** %s\n", classification.VulnerabilityClass))
			sb.WriteString(fmt.Sprintf("- **Attack Surface:** %s\n", classification.AttackSurface))
			sb.WriteString(fmt.Sprintf("- **Impact:** %s\n", classification.Impact))
			sb.WriteString(fmt.Sprintf("- **Scanner:** %s\n\n", f.Scanner))
			sb.WriteString(f.Description + "\n\n")

			if f.CodeSnippet != "" {
				sb.WriteString("```\n")
				sb.WriteString(f.CodeSnippet + "\n")
				sb.WriteString("```\n\n")
			}

			if f.Remediation != "" {
				sb.WriteString("**Remediation:**\n\n")
				sb.WriteString(f.Remediation + "\n\n")
			}

			if f.CVSSScore > 0 {
				sb.WriteString(fmt.Sprintf("- **CVSS Score:** %.1f\n", f.CVSSScore))
			}
			if f.CVSSVector != "" {
				sb.WriteString(fmt.Sprintf("- **CVSS Vector:** `%s`\n", f.CVSSVector))
			}
			if f.CWE != "" {
				sb.WriteString(fmt.Sprintf("- **CWE:** %s\n", f.CWE))
			}
			if f.OWASP != "" {
				sb.WriteString(fmt.Sprintf("- **OWASP:** %s\n", f.OWASP))
			}
			if len(classification.Compliance) > 0 {
				sb.WriteString(fmt.Sprintf("- **Compliance:** %s\n", strings.Join(classification.Compliance, ", ")))
			}

			if len(f.References) > 0 {
				sb.WriteString("**References:**\n")
				for _, ref := range f.References {
					sb.WriteString(fmt.Sprintf("- %s\n", ref))
				}
				sb.WriteString("\n")
			}

			sb.WriteString("---\n\n")
		}
	}

	sb.WriteString(fmt.Sprintf("*Generated by [Vanguard](https://github.com/your-repo/vanguard) %s*\n", r.Version))

	outPath := filepath.Join(r.OutputDir, "vanguard-report.md")
	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing Markdown report to %s: %w", outPath, err)
	}

	return nil
}

func severityEmoji(s models.Severity) string {
	switch s {
	case models.SeverityCritical:
		return "[CRITICAL]"
	case models.SeverityHigh:
		return "[HIGH]"
	case models.SeverityMedium:
		return "[MEDIUM]"
	case models.SeverityLow:
		return "[LOW]"
	default:
		return "[INFO]"
	}
}

func filterFindings(findings []models.Finding, sev models.Severity) []models.Finding {
	var result []models.Finding
	for _, f := range findings {
		if f.Severity == sev {
			result = append(result, f)
		}
	}
	return result
}
